---

# Playbook which installs a single node persistant RHMAP MBaaS

- name: "Prepare infrastructure for installation"
  hosts: mbaas
  remote_user: root
  roles:
    - {role: preflight_checks, tags: preflight_checks}
  vars_files:
    - "../roles/preflight_checks/vars/1-node-mbaas.yml"

- name: "Check for and update to nodejs 6 for image-streams"
  hosts: master
  roles:
    - {role: image-streams, tags: preflight_checks}
  vars_files:
    - "../roles/preflight_checks/vars/1-node-mbaas.yml"

- name: "Enable Docker to access container images of RHMAP components"
  hosts: master,core
  remote_user: root
  roles:
    - {role: rhmap-rpm, tags: rpm}

- name: "Install 1 node RHMAP MBaaS"
  hosts: master
  remote_user: root
  roles:
    - { role: deploy-mbaas, tags: deploy}
  vars_files:
    - "../roles/preflight_checks/vars/1-node-mbaas.yml"
