---
galaxy_info:
  author: AeroGear
  description: Provisioning of macOS slave for AeroGear digger
  company: AeroGear
  issue_tracker_url: https://issues.jboss.org/projects/AGDIGGER/issues
  license: license (Apache 2)

  platforms:
  - name: provision-osx

  galaxy_tags:
  - digger
  - macos
  - osx
  - mac

dependencies: []